# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#- trigger:
# - master

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_chemputer'
    userRepository: 'martinpaljak/GlobalPlatformPro'
    defaultVersionType: 'latest'
    itemPattern: '*.exe'
    downloadPath: '$(System.ArtifactsDirectory)'

steps:
- script: 
  displayName: 'Run a one-line script'
