# Starter pipeline
steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_chemputer'
    userRepository: 'martinpaljak/GlobalPlatformPro'
    defaultVersionType: 'latest'
    itemPattern: '*.exe'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $repo = "martinpaljak/GlobalPlatformPro"
      $file = "gp.exe"
      
      $releases = "https://api.github.com/repos/$repo/releases"
      $download = "https://github.com/$repo/releases/download/$tag/$file"
      $choco.url = [string]$download
      $version = $tag.substring(1)
      $choco.version = $version
      Invoke-WebRequest $download -Out $PsScriptRoot\tools\$file
      $hash = (Get-FileHash -File $PSScriptRoot\tools\$file -Algorithm SHA256)
      $choco.hash = [string]$hash
    errorActionPreference: 'silentlyContinue'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#- trigger:
# - master

- script: 
  displayName: $(hash)
